# Generated by Django 4.2.11 on 2024-03-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField(blank=True, verbose_name='Application Submission Date')),
                ('position', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('enthusiasm', models.CharField(choices=[('1', '😐 Neutral'), ('2', '😃 Happy '), ('3', '😍 Excited')], default='1', max_length=1)),
                ('work_arrangement', models.CharField(choices=[('R', 'Remote'), ('H', 'Hybrid'), ('O', 'On-site')], default='R', max_length=1, verbose_name='Work Arrangement')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='AL', max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('techstack', models.TextField(max_length=100, verbose_name='Technology Stack')),
                ('status', models.CharField(choices=[('A', 'Applied'), ('Y', 'Yet to Apply'), ('I', 'Interviewing'), ('N', 'Negotiating'), ('O', 'Accepted'), ('D', 'Decline'), ('R', 'Rejected')], default='A', max_length=1)),
                ('minsalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('maxsalary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('notes', models.TextField(max_length=1000)),
                ('application_type', models.CharField(choices=[('R', 'Referal'), ('C', 'Company Portal'), ('L', 'LinkedIn'), ('M', 'Monster'), ('G', 'Glassdoor'), ('L', 'LinkUp'), ('S', 'SimplyHired'), ('Z', 'ZipRecruiter'), ('I', 'Indeed')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_date', models.DateField(blank=True, verbose_name='Date')),
                ('position', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('letter', models.TextField(blank=True, max_length=2500, verbose_name='Cover Letter')),
                ('tags', models.CharField(max_length=250, verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coverletter')),
            ],
        ),
    ]
