# Generated by Django 4.2.11 on 2024-03-06 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='Interview Date')),
                ('interviewType', models.CharField(choices=[('P', 'Phone Screen'), ('T', 'Technical'), ('C', 'Cultural-Fit'), ('O', 'On-Site'), ('S', 'System-Design'), ('C', 'Code-Review')], default='P', max_length=1, verbose_name='Interview Type')),
                ('notes', models.TextField(default='', max_length=100)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
