# Generated by Django 4.2.10 on 2024-03-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_location_application_city_application_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(blank=True, verbose_name='Application Submission Date'),
        ),
        migrations.AlterField(
            model_name='application',
            name='maxsalary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary'),
        ),
        migrations.AlterField(
            model_name='application',
            name='minsalary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary'),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='techstack',
            field=models.TextField(max_length=100, verbose_name='Technology Stack'),
        ),
    ]
