# Generated by Django 4.2.10 on 2024-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_application_user_alter_application_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, verbose_name='createdDate')),
                ('letter', models.TextField(blank=True, max_length=2500)),
                ('tags', models.CharField(max_length=250, verbose_name='Tags')),
            ],
        ),
    ]
