# Generated by Django 4.2.11 on 2024-03-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_document_cl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coverletter'),
        ),
    ]
