# Generated by Django 4.2.10 on 2024-03-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_coverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='date',
            field=models.DateField(blank=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='letter',
            field=models.TextField(blank=True, max_length=2500, verbose_name='Cover Letter'),
        ),
    ]
