# Generated by Django 4.2.11 on 2024-03-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_document_cl'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
