# Generated by Django 4.2.11 on 2024-03-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_coverletter_position_alter_coverletter_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
        ),
    ]
