# Generated by Django 4.2.11 on 2024-03-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_document_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
