# Generated by Django 4.2.11 on 2024-03-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='app',
        ),
        migrations.AddField(
            model_name='application',
            name='applicationType',
            field=models.CharField(choices=[('R', 'Referal'), ('C', 'Company Portal'), ('L', 'LinkedIn'), ('M', 'Monster'), ('G', 'Glassdoor'), ('L', 'LinkUp'), ('S', 'SimplyHired'), ('Z', 'ZipRecruiter'), ('I', 'Indeed')], default='R', max_length=1),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Feeding Date')),
                ('interviewType', models.CharField(choices=[('P', 'Phone Screen'), ('T', 'Technical'), ('C', 'Cultural-Fit'), ('O', 'On-Site'), ('S', 'System-Design'), ('C', 'Code-Review')], default='P', max_length=1, verbose_name='Interview Type')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.application')),
            ],
        ),
    ]
