# Generated by Django 4.2.11 on 2024-03-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_document_app_application_applicationtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(verbose_name='Interview Date'),
        ),
    ]
