# Generated by Django 4.2.11 on 2024-03-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_interview_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='interview',
            name='notes',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='interview',
            name='time',
            field=models.TimeField(default=1),
            preserve_default=False,
        ),
    ]
