# Generated by Django 4.2.11 on 2024-03-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_interview_options_interview_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='time',
        ),
    ]
