# Generated by Django 4.2.11 on 2024-03-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_interview_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(blank=True, verbose_name='Interview Date'),
        ),
    ]
