# Generated by Django 4.2.11 on 2024-03-06 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_interview_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
